name: Build RTL8812AU for A9 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout driver
      uses: actions/checkout@v3

    - name: Clone kernel source
      run: |
        git clone https://github.com/thongass000/android_kernel_samsung_a9y18qlte.git kernel

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential bc kmod git flex bison libssl-dev

    - name: Build module
      run: |
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
          KERNEL_SRC=./kernel \
          CONFIG_PLATFORM_ARM64_ANDROID=y \
          CONFIG_PLATFORM_ANDROID=y

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rtl8812au-ko
        path: *.ko
